### ISSUE TITLE
Padawan crash

### ISSUE THREAD

**Issue by yriveiro** [pbogut/deoplete-padawan#22]
I have this errors in neovim all the time.

I don't now if it's related to deoplete or padawant it self, but always happen when autocomplete it's triggered.

```bash
[deoplete]     timeout=3
Padawan.php server started automatically
[deoplete]   File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 223, in urlopen
Padawan.php server started automatically
[deoplete]     return opener.open(url, data, timeout)
[deoplete]   File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 526, in open
[deoplete]     response = self._open(req, data)
[deoplete]   File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 544, in _open
[deoplete]     '_open', req)
[deoplete]   File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 504, in _call_chain
[deoplete]     result = func(*args)
[deoplete]   File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 1346, in http_open
[deoplete]     return self.do_open(http.client.HTTPConnection, req)
[deoplete]   File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 1321, in do_open
[deoplete]     r = h.getresponse()
[deoplete]   File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1331, in getresponse
[deoplete]     response.begin()
[deoplete]   File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 297, in begin
[deoplete]     version, status, reason = self._read_status()
[deoplete]   File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 266, in _read_status
[deoplete]     raise RemoteDisconnected("Remote end closed connection without"
[deoplete] http.client.RemoteDisconnected: Remote end closed connection without response
[deoplete] Could not get completions from: padawan.  Use :messages for error details.
[deoplete] Traceback (most recent call last):
"src/Dot.php" 178L, 3907C written
[deoplete]   File "/Users/yriveiro/.config/nvim/plugged/deoplete.nvim/rplugin/python3/deoplete/deoplete.py", line 135, in gather_results
[deoplete]     ctx['candidates'] = source.gather_candidates(ctx)
[deoplete]   File "/Users/yriveiro/.config/nvim/plugged/deoplete-padawan/rplugin/python3/deoplete/sources/deoplete_padawan.py", line 107, in gather_candidates
[deoplete]     result = self.do_request('complete', params, contents)
[deoplete]   File "/Users/yriveiro/.config/nvim/plugged/deoplete-padawan/rplugin/python3/deoplete/sources/deoplete_padawan.py", line 159, in do_request
```

I'm using Neovim 0.2.1 on OSX (El Capitan) 10.11.6

**Comment by pbogut** [comment]
What version of Padawan are you using, if 2.1 then can you try master?

Server log should be helpful as it looks like connection with server is lost. If plugin is starting padawan server for you then log should be in `/tmp/padawan-server.log` you can `tail -f /tmp/padawan-server.log` and see whats going on when you using plugin in neovim.

I have no OSX to check it, but I would assume it should not be different then linux.

**Comment by pbogut** [comment]
Close due to lack of response, feel free to reopen if issue persist.
